#!/usr/bin/env bash

# Theme Selector Script for Xenos Config
# Manages themes across multiple applications
THEMES_DIR="$HOME/.config/limitless/themes"
ROFI_CONFIG="$HOME/.config/rofi/styles/rofi.rasi"
NVIM_CONFIG="$HOME/.config/nvim/lua/plugins/theme.lua"
KITTY_CONFIG="$HOME/.config/kitty/kitty-theme.conf"
HYPERLAND_CONFIG="$HOME/.config/hypr/hyprland-theme.lua"
FOOT_CONFIG="$HOME/.config/foot/foot-theme.conf"
# Get list of available themes
get_themes() {
    if [[ ! -d "$THEMES_DIR" ]]; then
        echo "Error: Themes directory not found!"
        exit 1
    fi
   
    # Get unique theme names (without file extensions)
    find "$THEMES_DIR" -type d -mindepth 1 -maxdepth 1 -exec basename {} \; | sort
}
# Safe notification function
send_notification() {
    if command -v notify-send &> /dev/null && pgrep -x dunst &> /dev/null || pgrep -x mako &> /dev/null; then
        notify-send "$@" 2>/dev/null
    else
        echo "Notification: $1 - $2"
    fi
}
# Apply theme based on selection
apply_theme() {
    local theme_name="$1"
    local theme_path="$THEMES_DIR/$theme_name"
   
    if [[ ! -d "$theme_path" ]]; then
        send_notification "Theme Selector" "Theme '$theme_name' not found!" -u critical
        exit 1
    fi
   
    local applied=0
   
    # Apply Rofi theme
    if [[ -f "$theme_path/rofi.rasi" ]]; then
        cp "$theme_path/rofi.rasi" "$ROFI_CONFIG"
        echo "✓ Rofi theme applied"
        ((applied++))
    fi
   
    # Apply Neovim theme
    if [[ -f "$theme_path/nvim.lua" ]]; then
        mkdir -p "$(dirname "$NVIM_CONFIG")"
        cp "$theme_path/nvim.lua" "$NVIM_CONFIG"
        echo "✓ Neovim theme applied"
        ((applied++))
    fi
   
    # Apply Kitty theme
    if [[ -f "$theme_path/kitty-theme.conf" ]]; then
        cp "$theme_path/kitty-theme.conf" "$KITTY_CONFIG"
       
        # Reload kitty
        killall -SIGUSR1 kitty 2>/dev/null
        echo "✓ Kitty theme applied"
        ((applied++))
    fi

    # Apply Hyprland theme
    if [[ -f "$theme_path/hyprland-theme.lua" ]]; then
        cp "$theme_path/hyprland-theme.lua" "$HYPERLAND_CONFIG"
        echo "✓ Hyprland theme applied"
        ((applied++))
    fi

    # Apply Foot theme
    if [[ -f "$theme_path/foot-theme.ini" ]]; then
        cp "$theme_path/foot-theme.ini" "$FOOT_CONFIG"
        killall -SIGUSR1 foot 2>/dev/null
        echo "✓ Foot theme applied"
        ((applied++))
    fi
   
    # Apply other app configs if they exist
    if [[ -f "$theme_path/waybar-theme.css" ]] && [[ -d "$HOME/.config/waybar" ]]; then
        cp "$theme_path/waybar-theme.css" "$HOME/.config/waybar/waybar-theme.css"
        killall -SIGUSR2 waybar 2>/dev/null
        echo "✓ Waybar theme applied"
        ((applied++))
    fi

    # Apply EWW theme (converts waybar-theme.css @define-color to SCSS vars)
    if [[ -f "$theme_path/waybar-theme.css" ]] && [[ -d "$HOME/.config/eww" ]]; then
        {
            echo "// Generated by theme.sh - do not edit"
            sed -n 's/^@define-color \([a-z0-9_]*\)[[:space:]]*\(.*\);$/$\1: \2;/p' "$theme_path/waybar-theme.css"
        } > "$HOME/.config/eww/colors.scss"
        if command -v eww &>/dev/null && eww ping &>/dev/null; then
            eww reload 2>/dev/null
        fi
        echo "✓ EWW theme applied"
        ((applied++))
    fi

    # Apply SwayNC theme (no @import/@define-color support - swap hex values in style.css)
    SWAYNC_STYLE="$HOME/.config/swaync/style.css"
    if [[ -f "$SWAYNC_STYLE" ]]; then
        cur_theme=$(cat "$HOME/.config/limitless/current_theme" 2>/dev/null)
        [[ -z "$cur_theme" ]] && cur_theme="catppuccin-mocha"
        old_colors="$THEMES_DIR/$cur_theme/swaync-theme.css"
        if [[ ! -f "$old_colors" ]]; then
            sed -n 's/^@define-color \([a-z0-9_]*\)[[:space:]]*\(.*\);$/\1 \2/p' "$THEMES_DIR/$cur_theme/waybar-theme.css" > /tmp/opencode/swaync-old-colors.txt
            old_colors="/tmp/opencode/swaync-old-colors.txt"
        fi
        tmp_colors=""
        if [[ -f "$theme_path/swaync-theme.css" ]]; then
            new_colors="$theme_path/swaync-theme.css"
        else
            new_colors="$(mktemp)"
            sed -n 's/^@define-color \([a-z0-9_]*\)[[:space:]]*\(.*\);$/\1 \2/p' "$theme_path/waybar-theme.css" > "$new_colors"
            tmp_colors="$new_colors"
        fi
        exprs=()
        while read -r name old_hex; do
            new_hex=$(sed -n "s/^@define-color ${name}[[:space:]]*\(.*\);$/\1/p" "$new_colors")
            if [[ -n "$new_hex" && -n "$old_hex" && "$new_hex" != "$old_hex" ]]; then
                exprs+=("-e" "s/${old_hex}/${new_hex}/g")
            fi
        done < <(sed -n 's/^@define-color \([a-z0-9_]*\)[[:space:]]*\(.*\);$/\1 \2/p' "$old_colors")
        if [[ ${#exprs[@]} -gt 0 ]]; then
            sed -i "${exprs[@]}" "$SWAYNC_STYLE"
        fi
        [[ -n "$tmp_colors" ]] && rm -f "$tmp_colors"
        pkill -x swaync 2>/dev/null
        setsid swaync >/dev/null 2>&1 &
        echo "✓ SwayNC theme applied"
        ((applied++))
    fi
   
    if [[ -f "$theme_path/dunst.conf" ]] && [[ -d "$HOME/.config/dunst" ]]; then
        cp "$theme_path/dunst.conf" "$HOME/.config/dunst/dunstrc"
        killall dunst 2>/dev/null
        echo "✓ Dunst theme applied"
        ((applied++))
    fi
   
    # Apply random wallpaper if directory exists
    if [[ -d "$theme_path/wallpapers" ]]; then
        wallpaper=$(find "$theme_path/wallpapers" -type f -iregex '.*\.\(jpg\|jpeg\|png\|gif\)' | shuf -n 1)
        if [[ -n "$wallpaper" ]]; then
            # Set wallpaper using awww (common for Hyprland; adjust if using a different tool like hyprpaper)
            if command -v awww &> /dev/null; then
                awww img "$wallpaper"
                echo "✓ Random wallpaper applied from $theme_name"
                ((applied++))
            else
                send_notification "Theme Selector" "awww not found; wallpaper not applied" -u normal
                echo "Warning: awww not found; skipping wallpaper"
            fi
        else
            send_notification "Theme Selector" "No wallpapers found in $theme_path/wallpapers" -u normal
            echo "No wallpapers found in $theme_path/wallpapers"
        fi
    else
        echo "No wallpapers directory for $theme_name"
    fi
   
    # Save current theme
    mkdir -p "$HOME/.config/limitless"
    echo "$theme_name" > "$HOME/.config/limitless/current_theme"
   
    # Send notification
    send_notification "Theme Applied" "$theme_name theme applied to $applied applications" -u normal
}

# Get current theme
get_current_theme() {
    if [[ -f "$HOME/.config/limitless/current_theme" ]]; then
        cat "$HOME/.config/limitless/current_theme"
    else
        echo "none"
    fi
}
# Main function
main() {
    local current_theme=$(get_current_theme)
    local themes=$(get_themes)
   
    if [[ -z "$themes" ]]; then
        send_notification "Theme Selector" "No themes found in $THEMES_DIR" -u critical
        exit 1
    fi
   
    # Show rofi grid: horizontal list of theme icons
    selected=$(
        while IFS= read -r theme; do
            printf "%s\x00icon\x1f%s\n" "$theme" "$THEMES_DIR/$theme/logo.png"
        done <<< "$themes" | rofi -dmenu -i -p "" -show-icons -theme themes.rasi
    )

    if [[ -n "$selected" ]]; then
        apply_theme "$selected"
    fi
}
# Run main function
main
